version: '2'

services:
    app:
      container_name: m2-app
      image: luckyraul/docker-dummy
      volumes:
        - ./application:/var/www/public
    php:
      container_name: m2-php
      build:
        context: ./docker/xdebug
        args:
          - HOST_ARG=$HOST_ARG
      volumes_from:
       - app
      links:
       - db
      environment:
        - APPLICATION_MODE=development
        - PHPFPM_USER=$USERID
    nginx:
      container_name: m2-nginx
      image: luckyraul/nginx:backports
      environment:
        - NGINX_USER=$USERID
      ports:
       - 8081:80
      volumes:
        - ./conf/nginx:/etc/nginx/sites-enabled/
      volumes_from:
       - app
      depends_on:
       - php
    db:
      container_name: m2-db
      image: mygento/mysql
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb_file_per_table
      ports:
       - 3306:3306
      environment:
       - MYSQL_ROOT_PASSWORD=mygento
       - MYSQL_DATABASE=magento
       - MYSQL_USER=mygento
       - MYSQL_PASSWORD=mygento
      volumes:
       - "m2-db-data:/var/lib/mysql"
volumes:
    m2-db-data:
